def user(name, surname, tel, adress, code):
    print("="*40)  
    print("        User Information")
    print("="*40)  
    print(f"Name      : {name}")
    print(f"Surname   : {surname}")
    print(f"Phone     : {tel}")
    print(f"Address   : {adress}")
    print(f"Code      : {code}")
    print("="*40) 