print("1. Learning Python is fun!")
print("2. Python is great for data science.")
print("3. Python supports multiple programming paradigms.")
print("4. Python's syntax is clear and easy to understand.")
print("5. Python has a large community.")
print("6. Python is widely used in machine learning.")
print("7. Python has many libraries like NumPy and pandas.")
print("8. Python can be used for web development.")
print("9. Python integrates well with other languages.")
print("10. Python is popular in academia and research.")
print("11. Python is used for automation scripts.")
print("12. Python is used in artificial intelligence.")
print("13. Python is beginner-friendly.")
print("14. Python is used in data visualization.")
print("15. Python can handle big data processing.")
print("16. Python is open-source and free to use.")
print("17. Python has frameworks like Django and Flask.")
print("18. Python is used in software development.")
print("19. Python can be used for game development.")
print("20. Python's popularity continues to grow.") 