name = input("შეიყვანეთ სახელი: ")
surname = input("შეიყვანეთ გვარი: ")
age = input("შეიყვანეთ ასაკი: ")
number1 = input("შეიყვანეთ პირველი რიცხვი: ")
number2 = input("შეიყვანეთ მეორე რიცხვი: ")

print("სახელი:", name)
print("გვარი:", surname)
print("ასაკი:", age)
print("პირველი რიცხვი:", number1)
print("მეორე რიცხვი:", number2)
